name: Metrics

concurrency:
  group: metrics-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: "metrics 1"
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          filename: metrics-1.svg
          config_presets: https://raw.githubusercontent.com/saitenntaisei/saitenntaisei/main/metrics-presets/preset-1.yml
      - name: "metrics 2"
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          filename: metrics-2.svg
          config_presets: https://raw.githubusercontent.com/saitenntaisei/saitenntaisei/main/metrics-presets/preset-2.yml
