name: Metrics

concurrency:
  group: metrics-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "metrics 1"
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          filename: metrics-1.svg
          config_presets: https://raw.githubusercontent.com/saitenntaisei/saitenntaisei/main/metrics-presets/preset-1.yml
      - name: "metrics 2"
        uses: stalomeow/metrics@projects-v2
        with:
          debug: yes
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          filename: metrics-2.svg
          config_presets: https://raw.githubusercontent.com/saitenntaisei/saitenntaisei/main/metrics-presets/preset-2.yml
